# run by using `docker-compose up`
version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  db-admin:
    image: dpage/pgadmin4:7.7
    environment:
      PGADMIN_DEFAULT_EMAIL: user
      PGADMIN_DEFAULT_PASSWORD: 0
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - db