# run by using `docker-compose up`
version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5444:5444"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: -p 5444
  db-admin:
    image: dpage/pgadmin4:7.7
    environment:
      PGADMIN_DEFAULT_EMAIL: s@s.com
      PGADMIN_DEFAULT_PASSWORD: 0
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    depends_on:
      - db